######################## default configuration ####################
baseURL = "https://abufari.github.io/"
theme = "bigspring-light"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "70"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
